//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMISDemo.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResourceUnitTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResourceUnitTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMISDemo.Core.Resource.MISAResourceUnitTest", typeof(MISAResourceUnitTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host=8.222.228.150; Port=3306; Database=W08.NVTruc.MF1781; User Id=nvmanh; Password=12345678;.
        /// </summary>
        public static string ConnectString {
            get {
                return ResourceManager.GetString("ConnectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vantruc@gmail.com.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vantruc.txt.
        /// </summary>
        public static string EmailFalse {
            get {
                return ResourceManager.GetString("EmailFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NV-00508.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\\GD2\\BE\\MISA.AMISDemo.Api\\ExcelFile\\tiendo.txt.
        /// </summary>
        public static string ExcelFilePath {
            get {
                return ResourceManager.GetString("ExcelFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\\GD2\\BE\\MISA.AMISDemo.Api\\ExcelFile\\Danh_sach_nhan_vien.xlsx.
        /// </summary>
        public static string ExcelFilePathExcel {
            get {
                return ResourceManager.GetString("ExcelFilePathExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0999999999.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0974263636.
        /// </summary>
        public static string PhoneNumberFalse {
            get {
                return ResourceManager.GetString("PhoneNumberFalse", resourceCulture);
            }
        }
    }
}
